/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGeneratedImageRouteImport } from './routes/api/generated-image'
import { Route as ApiDownloadImageRouteImport } from './routes/api/download-image'
import { Route as ApiHistoryIndexRouteImport } from './routes/api/history/index'
import { Route as ApiUploadsInputImageRouteImport } from './routes/api/uploads/input-image'
import { Route as ApiUploadsAvatarRouteImport } from './routes/api/uploads/avatar'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiProviderResultArchiveThumbnailBackfillRouteImport } from './routes/api/provider-result-archive/thumbnail-backfill'
import { Route as ApiProviderResultArchiveClaimRouteImport } from './routes/api/provider-result-archive/claim'
import { Route as ApiProviderResultArchiveJobIdRouteImport } from './routes/api/provider-result-archive/$jobId'
import { Route as ApiProviderInputImageAssetIdRouteImport } from './routes/api/provider-input-image/$assetId'
import { Route as ApiHistoryThumbnailRouteImport } from './routes/api/history/thumbnail'
import { Route as ApiConfigHistoryThumbnailsRouteImport } from './routes/api/config/history-thumbnails'
import { Route as ApiAuthRequestPasswordResetRouteImport } from './routes/api/auth/request-password-reset'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminVerifyAccessPasswordRouteImport } from './routes/api/admin/verify-access-password'
import { Route as ApiAdminProviderTaskDiagnosticRouteImport } from './routes/api/admin/provider-task-diagnostic'
import { Route as ApiAccountProfileRouteImport } from './routes/api/account/profile'
import { Route as ApiAccountChangePasswordRouteImport } from './routes/api/account/change-password'
import { Route as ApiProviderResultArchiveThumbnailBackfillTaskIdRouteImport } from './routes/api/provider-result-archive/thumbnail-backfill/$taskId'
import { Route as ApiProviderResultArchiveJobIdThumbnailRouteImport } from './routes/api/provider-result-archive/$jobId/thumbnail'
import { Route as ApiProviderResultArchiveJobIdFailRouteImport } from './routes/api/provider-result-archive/$jobId/fail'

const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratedImageRoute = ApiGeneratedImageRouteImport.update({
  id: '/api/generated-image',
  path: '/api/generated-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadImageRoute = ApiDownloadImageRouteImport.update({
  id: '/api/download-image',
  path: '/api/download-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryIndexRoute = ApiHistoryIndexRouteImport.update({
  id: '/api/history/',
  path: '/api/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsInputImageRoute = ApiUploadsInputImageRouteImport.update({
  id: '/api/uploads/input-image',
  path: '/api/uploads/input-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsAvatarRoute = ApiUploadsAvatarRouteImport.update({
  id: '/api/uploads/avatar',
  path: '/api/uploads/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProviderResultArchiveThumbnailBackfillRoute =
  ApiProviderResultArchiveThumbnailBackfillRouteImport.update({
    id: '/api/provider-result-archive/thumbnail-backfill',
    path: '/api/provider-result-archive/thumbnail-backfill',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProviderResultArchiveClaimRoute =
  ApiProviderResultArchiveClaimRouteImport.update({
    id: '/api/provider-result-archive/claim',
    path: '/api/provider-result-archive/claim',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProviderResultArchiveJobIdRoute =
  ApiProviderResultArchiveJobIdRouteImport.update({
    id: '/api/provider-result-archive/$jobId',
    path: '/api/provider-result-archive/$jobId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProviderInputImageAssetIdRoute =
  ApiProviderInputImageAssetIdRouteImport.update({
    id: '/api/provider-input-image/$assetId',
    path: '/api/provider-input-image/$assetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHistoryThumbnailRoute = ApiHistoryThumbnailRouteImport.update({
  id: '/api/history/thumbnail',
  path: '/api/history/thumbnail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigHistoryThumbnailsRoute =
  ApiConfigHistoryThumbnailsRouteImport.update({
    id: '/api/config/history-thumbnails',
    path: '/api/config/history-thumbnails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthRequestPasswordResetRoute =
  ApiAuthRequestPasswordResetRouteImport.update({
    id: '/api/auth/request-password-reset',
    path: '/api/auth/request-password-reset',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminVerifyAccessPasswordRoute =
  ApiAdminVerifyAccessPasswordRouteImport.update({
    id: '/api/admin/verify-access-password',
    path: '/api/admin/verify-access-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminProviderTaskDiagnosticRoute =
  ApiAdminProviderTaskDiagnosticRouteImport.update({
    id: '/api/admin/provider-task-diagnostic',
    path: '/api/admin/provider-task-diagnostic',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAccountProfileRoute = ApiAccountProfileRouteImport.update({
  id: '/api/account/profile',
  path: '/api/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountChangePasswordRoute =
  ApiAccountChangePasswordRouteImport.update({
    id: '/api/account/change-password',
    path: '/api/account/change-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProviderResultArchiveThumbnailBackfillTaskIdRoute =
  ApiProviderResultArchiveThumbnailBackfillTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => ApiProviderResultArchiveThumbnailBackfillRoute,
  } as any)
const ApiProviderResultArchiveJobIdThumbnailRoute =
  ApiProviderResultArchiveJobIdThumbnailRouteImport.update({
    id: '/thumbnail',
    path: '/thumbnail',
    getParentRoute: () => ApiProviderResultArchiveJobIdRoute,
  } as any)
const ApiProviderResultArchiveJobIdFailRoute =
  ApiProviderResultArchiveJobIdFailRouteImport.update({
    id: '/fail',
    path: '/fail',
    getParentRoute: () => ApiProviderResultArchiveJobIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/inspiration': typeof InspirationRoute
  '/api/download-image': typeof ApiDownloadImageRoute
  '/api/generated-image': typeof ApiGeneratedImageRoute
  '/api/account/change-password': typeof ApiAccountChangePasswordRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/admin/provider-task-diagnostic': typeof ApiAdminProviderTaskDiagnosticRoute
  '/api/admin/verify-access-password': typeof ApiAdminVerifyAccessPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/request-password-reset': typeof ApiAuthRequestPasswordResetRoute
  '/api/config/history-thumbnails': typeof ApiConfigHistoryThumbnailsRoute
  '/api/history/thumbnail': typeof ApiHistoryThumbnailRoute
  '/api/provider-input-image/$assetId': typeof ApiProviderInputImageAssetIdRoute
  '/api/provider-result-archive/$jobId': typeof ApiProviderResultArchiveJobIdRouteWithChildren
  '/api/provider-result-archive/claim': typeof ApiProviderResultArchiveClaimRoute
  '/api/provider-result-archive/thumbnail-backfill': typeof ApiProviderResultArchiveThumbnailBackfillRouteWithChildren
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/uploads/avatar': typeof ApiUploadsAvatarRoute
  '/api/uploads/input-image': typeof ApiUploadsInputImageRoute
  '/api/history/': typeof ApiHistoryIndexRoute
  '/api/provider-result-archive/$jobId/fail': typeof ApiProviderResultArchiveJobIdFailRoute
  '/api/provider-result-archive/$jobId/thumbnail': typeof ApiProviderResultArchiveJobIdThumbnailRoute
  '/api/provider-result-archive/thumbnail-backfill/$taskId': typeof ApiProviderResultArchiveThumbnailBackfillTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/inspiration': typeof InspirationRoute
  '/api/download-image': typeof ApiDownloadImageRoute
  '/api/generated-image': typeof ApiGeneratedImageRoute
  '/api/account/change-password': typeof ApiAccountChangePasswordRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/admin/provider-task-diagnostic': typeof ApiAdminProviderTaskDiagnosticRoute
  '/api/admin/verify-access-password': typeof ApiAdminVerifyAccessPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/request-password-reset': typeof ApiAuthRequestPasswordResetRoute
  '/api/config/history-thumbnails': typeof ApiConfigHistoryThumbnailsRoute
  '/api/history/thumbnail': typeof ApiHistoryThumbnailRoute
  '/api/provider-input-image/$assetId': typeof ApiProviderInputImageAssetIdRoute
  '/api/provider-result-archive/$jobId': typeof ApiProviderResultArchiveJobIdRouteWithChildren
  '/api/provider-result-archive/claim': typeof ApiProviderResultArchiveClaimRoute
  '/api/provider-result-archive/thumbnail-backfill': typeof ApiProviderResultArchiveThumbnailBackfillRouteWithChildren
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/uploads/avatar': typeof ApiUploadsAvatarRoute
  '/api/uploads/input-image': typeof ApiUploadsInputImageRoute
  '/api/history': typeof ApiHistoryIndexRoute
  '/api/provider-result-archive/$jobId/fail': typeof ApiProviderResultArchiveJobIdFailRoute
  '/api/provider-result-archive/$jobId/thumbnail': typeof ApiProviderResultArchiveJobIdThumbnailRoute
  '/api/provider-result-archive/thumbnail-backfill/$taskId': typeof ApiProviderResultArchiveThumbnailBackfillTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/inspiration': typeof InspirationRoute
  '/api/download-image': typeof ApiDownloadImageRoute
  '/api/generated-image': typeof ApiGeneratedImageRoute
  '/api/account/change-password': typeof ApiAccountChangePasswordRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/admin/provider-task-diagnostic': typeof ApiAdminProviderTaskDiagnosticRoute
  '/api/admin/verify-access-password': typeof ApiAdminVerifyAccessPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/request-password-reset': typeof ApiAuthRequestPasswordResetRoute
  '/api/config/history-thumbnails': typeof ApiConfigHistoryThumbnailsRoute
  '/api/history/thumbnail': typeof ApiHistoryThumbnailRoute
  '/api/provider-input-image/$assetId': typeof ApiProviderInputImageAssetIdRoute
  '/api/provider-result-archive/$jobId': typeof ApiProviderResultArchiveJobIdRouteWithChildren
  '/api/provider-result-archive/claim': typeof ApiProviderResultArchiveClaimRoute
  '/api/provider-result-archive/thumbnail-backfill': typeof ApiProviderResultArchiveThumbnailBackfillRouteWithChildren
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/uploads/avatar': typeof ApiUploadsAvatarRoute
  '/api/uploads/input-image': typeof ApiUploadsInputImageRoute
  '/api/history/': typeof ApiHistoryIndexRoute
  '/api/provider-result-archive/$jobId/fail': typeof ApiProviderResultArchiveJobIdFailRoute
  '/api/provider-result-archive/$jobId/thumbnail': typeof ApiProviderResultArchiveJobIdThumbnailRoute
  '/api/provider-result-archive/thumbnail-backfill/$taskId': typeof ApiProviderResultArchiveThumbnailBackfillTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disclaimer'
    | '/inspiration'
    | '/api/download-image'
    | '/api/generated-image'
    | '/api/account/change-password'
    | '/api/account/profile'
    | '/api/admin/provider-task-diagnostic'
    | '/api/admin/verify-access-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/request-password-reset'
    | '/api/config/history-thumbnails'
    | '/api/history/thumbnail'
    | '/api/provider-input-image/$assetId'
    | '/api/provider-result-archive/$jobId'
    | '/api/provider-result-archive/claim'
    | '/api/provider-result-archive/thumbnail-backfill'
    | '/api/public/contact'
    | '/api/uploads/avatar'
    | '/api/uploads/input-image'
    | '/api/history/'
    | '/api/provider-result-archive/$jobId/fail'
    | '/api/provider-result-archive/$jobId/thumbnail'
    | '/api/provider-result-archive/thumbnail-backfill/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disclaimer'
    | '/inspiration'
    | '/api/download-image'
    | '/api/generated-image'
    | '/api/account/change-password'
    | '/api/account/profile'
    | '/api/admin/provider-task-diagnostic'
    | '/api/admin/verify-access-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/request-password-reset'
    | '/api/config/history-thumbnails'
    | '/api/history/thumbnail'
    | '/api/provider-input-image/$assetId'
    | '/api/provider-result-archive/$jobId'
    | '/api/provider-result-archive/claim'
    | '/api/provider-result-archive/thumbnail-backfill'
    | '/api/public/contact'
    | '/api/uploads/avatar'
    | '/api/uploads/input-image'
    | '/api/history'
    | '/api/provider-result-archive/$jobId/fail'
    | '/api/provider-result-archive/$jobId/thumbnail'
    | '/api/provider-result-archive/thumbnail-backfill/$taskId'
  id:
    | '__root__'
    | '/'
    | '/disclaimer'
    | '/inspiration'
    | '/api/download-image'
    | '/api/generated-image'
    | '/api/account/change-password'
    | '/api/account/profile'
    | '/api/admin/provider-task-diagnostic'
    | '/api/admin/verify-access-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/request-password-reset'
    | '/api/config/history-thumbnails'
    | '/api/history/thumbnail'
    | '/api/provider-input-image/$assetId'
    | '/api/provider-result-archive/$jobId'
    | '/api/provider-result-archive/claim'
    | '/api/provider-result-archive/thumbnail-backfill'
    | '/api/public/contact'
    | '/api/uploads/avatar'
    | '/api/uploads/input-image'
    | '/api/history/'
    | '/api/provider-result-archive/$jobId/fail'
    | '/api/provider-result-archive/$jobId/thumbnail'
    | '/api/provider-result-archive/thumbnail-backfill/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisclaimerRoute: typeof DisclaimerRoute
  InspirationRoute: typeof InspirationRoute
  ApiDownloadImageRoute: typeof ApiDownloadImageRoute
  ApiGeneratedImageRoute: typeof ApiGeneratedImageRoute
  ApiAccountChangePasswordRoute: typeof ApiAccountChangePasswordRoute
  ApiAccountProfileRoute: typeof ApiAccountProfileRoute
  ApiAdminProviderTaskDiagnosticRoute: typeof ApiAdminProviderTaskDiagnosticRoute
  ApiAdminVerifyAccessPasswordRoute: typeof ApiAdminVerifyAccessPasswordRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthRequestPasswordResetRoute: typeof ApiAuthRequestPasswordResetRoute
  ApiConfigHistoryThumbnailsRoute: typeof ApiConfigHistoryThumbnailsRoute
  ApiHistoryThumbnailRoute: typeof ApiHistoryThumbnailRoute
  ApiProviderInputImageAssetIdRoute: typeof ApiProviderInputImageAssetIdRoute
  ApiProviderResultArchiveJobIdRoute: typeof ApiProviderResultArchiveJobIdRouteWithChildren
  ApiProviderResultArchiveClaimRoute: typeof ApiProviderResultArchiveClaimRoute
  ApiProviderResultArchiveThumbnailBackfillRoute: typeof ApiProviderResultArchiveThumbnailBackfillRouteWithChildren
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiUploadsAvatarRoute: typeof ApiUploadsAvatarRoute
  ApiUploadsInputImageRoute: typeof ApiUploadsInputImageRoute
  ApiHistoryIndexRoute: typeof ApiHistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generated-image': {
      id: '/api/generated-image'
      path: '/api/generated-image'
      fullPath: '/api/generated-image'
      preLoaderRoute: typeof ApiGeneratedImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download-image': {
      id: '/api/download-image'
      path: '/api/download-image'
      fullPath: '/api/download-image'
      preLoaderRoute: typeof ApiDownloadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/': {
      id: '/api/history/'
      path: '/api/history'
      fullPath: '/api/history/'
      preLoaderRoute: typeof ApiHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/input-image': {
      id: '/api/uploads/input-image'
      path: '/api/uploads/input-image'
      fullPath: '/api/uploads/input-image'
      preLoaderRoute: typeof ApiUploadsInputImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/avatar': {
      id: '/api/uploads/avatar'
      path: '/api/uploads/avatar'
      fullPath: '/api/uploads/avatar'
      preLoaderRoute: typeof ApiUploadsAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider-result-archive/thumbnail-backfill': {
      id: '/api/provider-result-archive/thumbnail-backfill'
      path: '/api/provider-result-archive/thumbnail-backfill'
      fullPath: '/api/provider-result-archive/thumbnail-backfill'
      preLoaderRoute: typeof ApiProviderResultArchiveThumbnailBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider-result-archive/claim': {
      id: '/api/provider-result-archive/claim'
      path: '/api/provider-result-archive/claim'
      fullPath: '/api/provider-result-archive/claim'
      preLoaderRoute: typeof ApiProviderResultArchiveClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider-result-archive/$jobId': {
      id: '/api/provider-result-archive/$jobId'
      path: '/api/provider-result-archive/$jobId'
      fullPath: '/api/provider-result-archive/$jobId'
      preLoaderRoute: typeof ApiProviderResultArchiveJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider-input-image/$assetId': {
      id: '/api/provider-input-image/$assetId'
      path: '/api/provider-input-image/$assetId'
      fullPath: '/api/provider-input-image/$assetId'
      preLoaderRoute: typeof ApiProviderInputImageAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/thumbnail': {
      id: '/api/history/thumbnail'
      path: '/api/history/thumbnail'
      fullPath: '/api/history/thumbnail'
      preLoaderRoute: typeof ApiHistoryThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config/history-thumbnails': {
      id: '/api/config/history-thumbnails'
      path: '/api/config/history-thumbnails'
      fullPath: '/api/config/history-thumbnails'
      preLoaderRoute: typeof ApiConfigHistoryThumbnailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/request-password-reset': {
      id: '/api/auth/request-password-reset'
      path: '/api/auth/request-password-reset'
      fullPath: '/api/auth/request-password-reset'
      preLoaderRoute: typeof ApiAuthRequestPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/verify-access-password': {
      id: '/api/admin/verify-access-password'
      path: '/api/admin/verify-access-password'
      fullPath: '/api/admin/verify-access-password'
      preLoaderRoute: typeof ApiAdminVerifyAccessPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/provider-task-diagnostic': {
      id: '/api/admin/provider-task-diagnostic'
      path: '/api/admin/provider-task-diagnostic'
      fullPath: '/api/admin/provider-task-diagnostic'
      preLoaderRoute: typeof ApiAdminProviderTaskDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/profile': {
      id: '/api/account/profile'
      path: '/api/account/profile'
      fullPath: '/api/account/profile'
      preLoaderRoute: typeof ApiAccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/change-password': {
      id: '/api/account/change-password'
      path: '/api/account/change-password'
      fullPath: '/api/account/change-password'
      preLoaderRoute: typeof ApiAccountChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider-result-archive/thumbnail-backfill/$taskId': {
      id: '/api/provider-result-archive/thumbnail-backfill/$taskId'
      path: '/$taskId'
      fullPath: '/api/provider-result-archive/thumbnail-backfill/$taskId'
      preLoaderRoute: typeof ApiProviderResultArchiveThumbnailBackfillTaskIdRouteImport
      parentRoute: typeof ApiProviderResultArchiveThumbnailBackfillRoute
    }
    '/api/provider-result-archive/$jobId/thumbnail': {
      id: '/api/provider-result-archive/$jobId/thumbnail'
      path: '/thumbnail'
      fullPath: '/api/provider-result-archive/$jobId/thumbnail'
      preLoaderRoute: typeof ApiProviderResultArchiveJobIdThumbnailRouteImport
      parentRoute: typeof ApiProviderResultArchiveJobIdRoute
    }
    '/api/provider-result-archive/$jobId/fail': {
      id: '/api/provider-result-archive/$jobId/fail'
      path: '/fail'
      fullPath: '/api/provider-result-archive/$jobId/fail'
      preLoaderRoute: typeof ApiProviderResultArchiveJobIdFailRouteImport
      parentRoute: typeof ApiProviderResultArchiveJobIdRoute
    }
  }
}

interface ApiProviderResultArchiveJobIdRouteChildren {
  ApiProviderResultArchiveJobIdFailRoute: typeof ApiProviderResultArchiveJobIdFailRoute
  ApiProviderResultArchiveJobIdThumbnailRoute: typeof ApiProviderResultArchiveJobIdThumbnailRoute
}

const ApiProviderResultArchiveJobIdRouteChildren: ApiProviderResultArchiveJobIdRouteChildren =
  {
    ApiProviderResultArchiveJobIdFailRoute:
      ApiProviderResultArchiveJobIdFailRoute,
    ApiProviderResultArchiveJobIdThumbnailRoute:
      ApiProviderResultArchiveJobIdThumbnailRoute,
  }

const ApiProviderResultArchiveJobIdRouteWithChildren =
  ApiProviderResultArchiveJobIdRoute._addFileChildren(
    ApiProviderResultArchiveJobIdRouteChildren,
  )

interface ApiProviderResultArchiveThumbnailBackfillRouteChildren {
  ApiProviderResultArchiveThumbnailBackfillTaskIdRoute: typeof ApiProviderResultArchiveThumbnailBackfillTaskIdRoute
}

const ApiProviderResultArchiveThumbnailBackfillRouteChildren: ApiProviderResultArchiveThumbnailBackfillRouteChildren =
  {
    ApiProviderResultArchiveThumbnailBackfillTaskIdRoute:
      ApiProviderResultArchiveThumbnailBackfillTaskIdRoute,
  }

const ApiProviderResultArchiveThumbnailBackfillRouteWithChildren =
  ApiProviderResultArchiveThumbnailBackfillRoute._addFileChildren(
    ApiProviderResultArchiveThumbnailBackfillRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisclaimerRoute: DisclaimerRoute,
  InspirationRoute: InspirationRoute,
  ApiDownloadImageRoute: ApiDownloadImageRoute,
  ApiGeneratedImageRoute: ApiGeneratedImageRoute,
  ApiAccountChangePasswordRoute: ApiAccountChangePasswordRoute,
  ApiAccountProfileRoute: ApiAccountProfileRoute,
  ApiAdminProviderTaskDiagnosticRoute: ApiAdminProviderTaskDiagnosticRoute,
  ApiAdminVerifyAccessPasswordRoute: ApiAdminVerifyAccessPasswordRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthRequestPasswordResetRoute: ApiAuthRequestPasswordResetRoute,
  ApiConfigHistoryThumbnailsRoute: ApiConfigHistoryThumbnailsRoute,
  ApiHistoryThumbnailRoute: ApiHistoryThumbnailRoute,
  ApiProviderInputImageAssetIdRoute: ApiProviderInputImageAssetIdRoute,
  ApiProviderResultArchiveJobIdRoute:
    ApiProviderResultArchiveJobIdRouteWithChildren,
  ApiProviderResultArchiveClaimRoute: ApiProviderResultArchiveClaimRoute,
  ApiProviderResultArchiveThumbnailBackfillRoute:
    ApiProviderResultArchiveThumbnailBackfillRouteWithChildren,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiUploadsAvatarRoute: ApiUploadsAvatarRoute,
  ApiUploadsInputImageRoute: ApiUploadsInputImageRoute,
  ApiHistoryIndexRoute: ApiHistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
